### ISSUE TITLE
Installation fails (discourse-simplification dependency)

### ISSUE THREAD

**Issue by hate5six** [Lambda-3/Graphene#13]
When running the installation via `mvn clean package -DskipTests` I get the following error. How do I go about resolving this dependency? I've installed the Discourse and Sentence Simplification packages as outlined in the README

> [ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:2.0.0-SNAPSHOT: Fa                           ilure to find org.lambda3.text.simplification:discourse-simplification:jar:6.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository,                            resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by mithrial** [comment]
You have to run the two scripts from the repo to install the two dependencies.
[install-SentenceSimplification.sh](../blob/master/install-SentenceSimplification.sh)
[install-DiscourseSimplification.sh](../blob/master/install-DiscourseSimplification.sh)
