### ISSUE TITLE
Graphene-Core build problem

### ISSUE THREAD

**Issue by gkiril** [Lambda-3/Graphene#26]
I am following the installation manual both from the documentation and from this video: https://asciinema.org/a/bvhgIP8ZEgDwtmRPFctHyxALu?speed=3

However, when I get to build with `mvn clean package -DskipTests`, I get the following error:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] The Graphene Extraction Tool
[INFO] Graphene Core
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building The Graphene Extraction Tool 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ graphene ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ graphene ---
[INFO] Executing: /bin/sh -c cd '/home/gkiril/Documents/workspace/nlp_projects/relations/Graphene' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/gkiril/Documents/workspace/nlp_projects/relations/Graphene
[INFO] Storing buildNumber: 3d2387d2bea21d91fdf7873a4873479282d1b62f at timestamp: 1534430398441
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] --- license-maven-plugin:1.12:update-file-header (first) @ graphene ---
[WARNING] No file to scan.
[INFO] 
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ graphene ---
[INFO] Installing /home/gkiril/Documents/workspace/nlp_projects/relations/Graphene/pom.xml to /home/gkiril/.m2/repository/org/lambda3/graphene/graphene/3.0.0-SNAPSHOT/graphene-3.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Graphene Core 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.lambda3.text.simplification:discourse-simplification:jar:8.1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] The Graphene Extraction Tool ....................... SUCCESS [  1.158 s]
[INFO] Graphene Core ...................................... FAILURE [  0.089 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.346 s
[INFO] Finished at: 2018-08-16T16:39:59+02:00
[INFO] Final Memory: 18M/391M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:3.0.0-SNAPSHOT: Could not find artifact org.lambda3.text.simplification:discourse-simplification:jar:8.1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :graphene-core
```
Any tips of how to resolve this?

**Comment by Mischn** [comment]
Hello Kiril, thank you for the hint.

We have recently updated the **DiscourseSimplification**-project, which is imported by Graphene as a Maven dependency. This update has not been propagated properly to the Graphene project. I will fix this issue soon.

In the meantime, you can clone the DiscourseSimplification project:
`git clone https://github.com/Lambda-3/DiscourseSimplification`

 and run
`mvn clean install -DskipTests`

This should install the (newer) version **8.1.0-SNAPSHOT** into your local Maven repository

**Comment by gkiril** [comment]
Alright, that solved the building problem (thanks!). However, when I run an example sentence on the CLI: 

```
$ mvn exec:java -Dexec.args="--relationExtraction --output CMDLINE --format DEFAULT --input TEXT 'Although the Treasury will announce details of the November refunding on Monday, the funding will be delayed if Congress and President Bush fail to increase the Treasurys borrowing capacity.'" -Dconfig.file="../conf/graphene.conf" 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Graphene CLI 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ graphene-cli >>>
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ graphene-cli ---
[INFO] Executing: /bin/sh -c cd '/home/gkiril/Documents/workspace/nlp_projects/relations/Graphene/graphene-cli' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/gkiril/Documents/workspace/nlp_projects/relations/Graphene/graphene-cli
[INFO] Storing buildNumber: 3d2387d2bea21d91fdf7873a4873479282d1b62f at timestamp: 1534434349004
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ graphene-cli <<<
[WARNING] The POM for org.lambda3.graphene:graphene-core:jar:3.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.756 s
[INFO] Finished at: 2018-08-16T17:45:49+02:00
[INFO] Final Memory: 14M/602M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphene-cli: Could not resolve dependencies for project org.lambda3.graphene:graphene-cli:jar:3.0.0-SNAPSHOT: Could not find artifact org.lambda3.graphene:graphene-core:jar:3.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```
I still get an error. Is this again due to the versioning conflicts?

**Comment by Mischn** [comment]
glad to hear that!
did you run `mvn clean install -DskipTests` inside of you Graphene-Root directory?

**Comment by Mischn** [comment]
btw, some of the command line CLI arguments from the video have changed too.
See [this page](https://github.com/Lambda-3/Graphene/blob/master/wiki/Graphene-CLI.md) for the updated set of commands.

**Comment by gkiril** [comment]
Ah yes, I guess I skipped that part. It works now (and yes, it gave me errors before swapping back to the proper CLI arguments). 

Thanks a lot! It might be more helpful for future users to point these things out in the documentation.

Cheers!

**Comment by Mischn** [comment]
Great! I will update the documentation accordingly.
Thank you for your feedback!

**Comment by navjot-bham** [comment]
hi
i got the same issue and not able to solve it even after installing the discourseSimplification 

C:\graphene>mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] The Graphene Extraction Tool
[INFO] Graphene Core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building The Graphene Extraction Tool 3.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ graphene ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ graphene ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\graphene
[INFO] Storing buildNumber: ef84c23b43020b6abe6c703074f8273d4c0a4bba at timestamp: 1568578559568
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- license-maven-plugin:1.12:update-file-header (first) @ graphene ---
[WARNING] No file to scan.
[INFO]
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ graphene ---
[INFO] Installing C:\graphene\pom.xml to C:\Users\Hp\.m2\repository\org\lambda3\graphene\graphene\3.1.0\graphene-3.1.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Graphene Core 3.1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] The Graphene Extraction Tool ....................... SUCCESS [  3.236 s]
[INFO] Graphene Core ...................................... FAILURE [  0.375 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.783 s
[INFO] Finished at: 2019-09-16T06:16:01+10:00
[INFO] Final Memory: 14M/50M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:3.1.0: Failure to find org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :graphene-core

**Comment by usbader** [comment]
> hi
> i got the same issue and not able to solve it even after installing the discourseSimplification
> 
> C:\graphene>mvn clean install -DskipTests
> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO]
> [INFO] The Graphene Extraction Tool
> [INFO] Graphene Core
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building The Graphene Extraction Tool 3.1.0
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ graphene ---
> [INFO]
> [INFO] --- buildnumber-maven-plugin:1.4:create (default) @ graphene ---
> [INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
> [INFO] Working directory: C:\graphene
> [INFO] Storing buildNumber: [ef84c23](https://github.com/Lambda-3/Graphene/commit/ef84c23b43020b6abe6c703074f8273d4c0a4bba) at timestamp: 1568578559568
> [INFO] Storing buildScmBranch: master
> [INFO]
> [INFO] --- license-maven-plugin:1.12:update-file-header (first) @ graphene ---
> [WARNING] No file to scan.
> [INFO]
> [INFO]
> [INFO] --- maven-install-plugin:2.4:install (default-install) @ graphene ---
> [INFO] Installing C:\graphene\pom.xml to C:\Users\Hp.m2\repository\org\lambda3\graphene\graphene\3.1.0\graphene-3.1.0.pom
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Graphene Core 3.1.0
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] The Graphene Extraction Tool ....................... SUCCESS [ 3.236 s]
> [INFO] Graphene Core ...................................... FAILURE [ 0.375 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.783 s
> [INFO] Finished at: 2019-09-16T06:16:01+10:00
> [INFO] Final Memory: 14M/50M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:3.1.0: Failure to find org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :graphene-core

I am also having the same issue. Have you fixed it?

**Comment by mapto** [comment]
The current version of discourse-simplification is [8.2.1](https://github.com/Lambda-3/DiscourseSimplification/blob/master/pom.xml#L29).

To find this you need to:
1. Build DiscourseSimplification from source, as [explained above](https://github.com/Lambda-3/Graphene/issues/26#issuecomment-413586855).
2. Upgrade the [version dependency variable](https://github.com/Lambda-3/Graphene/blob/master/graphene-core/pom.xml#L18) in the pom.xml of Graphene-Core.

Even after doing this, I wasn't able to run graphene-cli (due to XML dependency issues), but I was able to run graphene-server following the instructions with docker.
