### ISSUE TITLE
Can't find the Maven dependencies

### ISSUE THREAD

**Issue by PhdStudent2015** [Lambda-3/Graphene#29]
Hi,
I try to use Graphene Java API, so  I added the dependency that you mentionned  to my pom.xml. However, Maven can't find it, same problem for the sentence simplification and discourse simplification respective dependencies. Is there any specific maven repository to add to my pom.xml ?

**Comment by Mischn** [comment]
Hi,
you probably forgot to install the Maven-Dependencies locally.
Did you ensure that you have executed the following commands?

`./install-SentenceSimplification.sh`
`./install-DiscourseSimplification.sh`
`mvn clean install -DskipTests`
