### ISSUE TITLE
No graphExtraction results from server when doCoreference=true

### ISSUE THREAD

**Issue by wnunderwood** [Lambda-3/Graphene#3]
Making a request like this yields good results:

curl -X POST -H "Content-Type: application/json"  -d '{"text": "The president lives in the White House and he flies in Airforce One", "doCoreference": "false", "doSimplification": "false"}' -H "Accept: application/json" "http://localhost:8080/graphExtraction/text"

However, flipping doCoreference to true returns nothing.  The logs from the server seem to end at the coreference request although there is no error message displayed.

graphene_1     | 18:36:34 qtp1597742167-13 - /graphExtraction/text DEBUG|o.l.graphene.core.Graphene doGraphExtraction - doGraphExtraction for text
graphene_1     | 18:36:34 qtp1597742167-13 - /graphExtraction/text DEBUG|o.l.graphene.core.Graphene doCoreference - doCoreference for text
graphene_1     | 18:36:34 qtp1597742167-13 - /graphExtraction/text DEBUG|o.l.g.c.c.Coreference sendRequest - Sending coreference request to http://localhost:5128/resolve/text

**Comment by mithrial** [comment]
From your log, I think that it sends the request for the coreference resolution to localhost. In the config file, you should specify the URL to the service. The newest commit  4c0beb16e737d8a7281b018f81e5aafc371e76e2 defaults to the path configured in the docker-compose.yml file instead of localhost.

**Comment by wnunderwood** [comment]
I've cloned and rebuilt from scratch and verified this config change is in place.  However it still seems to be looking to localhost.

graphene_1     | 20:09:05 main INFO |o.l.g.c.c.Coreference <init> - Will use remote coreference resource at: 'http://localhost:5128/resolve'
....
graphene_1     | 20:09:06 main INFO |o.l.graphene.core.Graphene <init> -
graphene_1     | {
graphene_1     |     "coreference" : {
graphene_1     |         "text-path" : "text",
graphene_1     |         "url" : "http://localhost:5128/resolve",
graphene_1     |         "wiki-link-path" : "link",
graphene_1     |         "wiki-path" : "wiki"
graphene_1     |     },

**Comment by wnunderwood** [comment]
D
