### ISSUE TITLE
mvn clean install -DskipTests fail

### ISSUE THREAD

**Issue by aryoxp** [Lambda-3/Graphene#30]
Hi,
I try to follow the installation steps and I got the following error:

[INFO] 
[INFO] -----------------< org.lambda3.graphene:graphene-core >-----------------
[INFO] Building Graphene Core 3.0.0-SNAPSHOT                              [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.lambda3.text.simplification:discourse-simplification:jar:8.1.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] The Graphene Extraction Tool 3.0.0-SNAPSHOT ........ SUCCESS [  1.277 s]
[INFO] Graphene Core 3.0.0-SNAPSHOT ....................... FAILURE [  0.175 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.568 s
[INFO] Finished at: 2018-10-17T12:55:31+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:3.0.0-SNAPSHOT: Failure to find org.lambda3.text.simplification:discourse-simplification:jar:8.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :graphene-core

Any ideas on how to resolve this problem?
Thanks.

**Comment by Mischn** [comment]
Hello,

I not able to reproduce your error, but you may want to pull the newest version of Graphene which uses the newest DiscourseSimplification version (8.1.1).
You can then install the DiscourseSimplification project into your local repository by executing the script:
```
install-DiscourseSimplification.sh
```

and try again.

Best
Matthias
