### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by Kiro02** [Lambda-3/Graphene#32]
Hi, I try to follow the installation steps and I got the following error when I execute `docker-compose up`:

```
graphene_corenlp_1 is up-to-date
graphene_coreference_1 is up-to-date
Starting graphene_graphene_1 ... error

ERROR: for graphene_graphene_1  Cannot start service graphene: oci runtime error: container_linux.go:247: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory"


ERROR: for graphene  Cannot start service graphene: oci runtime error: container_linux.go:247: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory"

ERROR: Encountered errors while bringing up the project.
```

Any tips of how to resolve this?

**Comment by Mischn** [comment]
Hello,

my first guess is that the docker image is disrupted.
You may try to rebuild the docker image and try again.
You can do this by using the --build flag:

`docker-compose up --build`

**Comment by Kiro02** [comment]
Thanks for your advice.
but I get a following error message after I used `docker-compose up --build`
`docker-compose                 docker-credential-osxkeychain
docker-compose.backup          
M007381-KiroOtsu:Graphene otsukiro$ docker-compose up --build
Building graphene
Step 1/5 : FROM openjdk:8-jre
 ---> 823dd2edb8ca
Step 2/5 : WORKDIR /usr/share/graphene
 ---> Using cache
 ---> 9cbfcacfb666
Step 3/5 : ENV LANG="en_US.UTF-8" TZ="Europe/Berlin"
 ---> Using cache
 ---> 9b29d72ea95d
Step 4/5 : EXPOSE 8080
 ---> Using cache
 ---> c852502286f6
Step 5/5 : CMD ["bin/start.sh"]
 ---> Using cache
 ---> 540d3345f441
Successfully built 540d3345f441
Successfully tagged graphene_graphene:latest
Recreating graphene_corenlp_1 ... 
Recreating graphene_corenlp_1 ... done
Recreating 9b3da4b925ae_graphene_coreference_1 ... 
Recreating 9b3da4b925ae_graphene_coreference_1 ... done
Creating graphene_graphene_1 ... 
Creating graphene_graphene_1 ... error

ERROR: for graphene_graphene_1  Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown

ERROR: for graphene  Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.`

I guess this "start.sh" is the one in Graphene/graphene-server/src/main/resources/
and I try to move this file to "bin/" ,but I cannot find that.

**Comment by Mischn** [comment]
Hello Kiro,

can you try it again with the `--no-cache` flag?
I want to get sure that the docker image is rebuilt from scratch.
