### ISSUE TITLE
installation issue with DiscourseSimplification on MacOS

### ISSUE THREAD

**Issue by Heipihanhan** [Lambda-3/Graphene#41]
There seems to be some issue with this line:`tar xfa DiscourseSimplification.tar.gz `

However, it worked when I change it to `tar -xf DiscourseSimplification.tar.gz `. 

I'm using MacOS Mojave Version 10.14.3.

**Comment by Mischn** [comment]
Thank you for the hint! We haven't tested Graphene on MacOS yet.
