### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by navjotkaurbham** [Lambda-3/Graphene#45]
i have installed the DiscourseSimplification even after installing finding the issue and not able to solve it...

C:\graphene>mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] The Graphene Extraction Tool
[INFO] Graphene Core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building The Graphene Extraction Tool 3.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ graphene ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ graphene ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\graphene
[INFO] Storing buildNumber: ef84c23b43020b6abe6c703074f8273d4c0a4bba at timestamp: 1568578559568
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- license-maven-plugin:1.12:update-file-header (first) @ graphene ---
[WARNING] No file to scan.
[INFO]
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ graphene ---
[INFO] Installing C:\graphene\pom.xml to C:\Users\Hp\.m2\repository\org\lambda3\graphene\graphene\3.1.0\graphene-3.1.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Graphene Core 3.1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] The Graphene Extraction Tool ....................... SUCCESS [  3.236 s]
[INFO] Graphene Core ...................................... FAILURE [  0.375 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.783 s
[INFO] Finished at: 2019-09-16T06:16:01+10:00
[INFO] Final Memory: 14M/50M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graphene-core: Could not resolve dependencies for project org.lambda3.graphene:graphene-core:jar:3.1.0: Failure to find org.lambda3.text.simplification:discourse-simplification:jar:8.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :graphene-core

**Comment by bermeitinger-b** [comment]
You have to manually install this dependency (https://github.com/Lambda-3/Graphene/blob/master/install-DiscourseSimplification.sh)
