### ISSUE TITLE
Unexpected character ('d' (code 100)): was expecting comma to separate Object entries

### ISSUE THREAD

**Issue by pramod2157** [Lambda-3/Graphene#46]
I ran below command:
curl -X POST -H "Content-Type: application/json"  -d '{"text": "Google was founded in 2006"doCoreference": "true", "isolateSentences": "false", "format": "DEFAULT"}' -H "Accept: text/plain" "http://localhost:8080/relationExtraction/text"

Getting below error:
Unexpected character ('d' (code 100)): was expecting comma to separate Object entries
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@7e11ff54; line: 1, column: 42](base)

**Comment by bermeitinger-b** [comment]
In your request, the parameters must be separated with a comma:

`curl -X POST -H "Content-Type: application/json" -d '{"text": "Google was founded in 2006", "doCoreference": "true", "isolateSentences": "false", "format": "DEFAULT"}' -H "Accept: text/plain" "http://localhost:8080/relationExtraction/text"`
